### ISSUE TITLE
Quotes and backslashes are stripped

### ISSUE THREAD

**Issue by bartasha** [LukeSavefrogs/column_ansi#6]
Quotes and backslashes present in the input do not appear in the output.  I've submitted a PR to fix this (#5).

**Comment by LukeSavefrogs** [comment]
Hi @bartasha!

Thanks for your contribution, i didn't notice this bug at all! 👀
I just accepted your pull request. 

Thank you again for taking the time to improve this little project! 🥇

**Comment by LukeSavefrogs** [comment]
@all-contributors add @bartasha for code
